services:
  postgres:
    image: postgres:15
    container_name: shopstream-postgres
    env_file:
      - .env
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: shopstream-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  orders:
    build: .
    container_name: shopstream-orders
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    command: >
      sh -c "
      scripts/wait-for-db.sh &&
      uvicorn services.orders.app.main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  outbox-publisher:
    build: .
    container_name: shopstream-outbox-publisher
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    command: python workers/outbox_publisher.py
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  inventory:
    build: .
    container_name: shopstream-inventory
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
    command: python services/inventory/app/consumer.py
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


volumes:
  postgres_data:
